# Generated by Django 3.0.7 on 2020-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='category_name',
            new_name='category_nameh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='description',
            new_name='commenth',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='item_name',
            new_name='descriptionh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='image',
            new_name='imageh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='item_fattal_code_begin',
            new_name='item_fattal_code_beginh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='item_fattal_code_end',
            new_name='item_fattal_code_endh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='item_fattal_code',
            new_name='item_fattal_codeh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='item_transfer_quantity',
            new_name='item_nameh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='sub_category_name',
            new_name='item_transferh_quantityh',
        ),
        migrations.RenameField(
            model_name='stockhistory',
            old_name='tem_transfer_to',
            new_name='item_transferh_toh',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='item_unit_kind',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('units in box', 'unit_in_box'), ('other', 'other'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='sub_category_nameh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='transfer_towhomh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
