# Generated by Django 3.0.7 on 2020-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0002_auto_20200627_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
