# Generated by Django 3.0.7 on 2020-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0010_auto_20200705_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('other', 'other'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
