# Generated by Django 3.0.7 on 2020-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0013_auto_20200706_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('grams', 'grams'), ('other', 'other'), ('liters', 'liters'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
    ]
