# Generated by Django 3.0.7 on 2020-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0016_auto_20200708_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('grams', 'grams'), ('other', 'other'), ('units in box', 'unit_in_box'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
