# Generated by Django 3.0.7 on 2020-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0017_auto_20200710_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
