# Generated by Django 3.0.7 on 2020-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0019_auto_20200710_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams')], max_length=50, null=True),
        ),
    ]
