# Generated by Django 3.0.7 on 2020-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0021_auto_20200711_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
