# Generated by Django 3.0.7 on 2020-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0022_auto_20200711_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
