# Generated by Django 3.0.7 on 2020-07-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0023_auto_20200711_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
