# Generated by Django 3.0.7 on 2020-07-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0024_auto_20200712_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
