# Generated by Django 3.0.7 on 2020-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_unit_kind', models.CharField(blank=True, choices=[('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg'), ('units in box', 'unit_in_box')], max_length=50, null=True)),
                ('tem_transfer_to', models.CharField(blank=True, max_length=50, null=True)),
                ('item_transfer_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('item_fattal_code', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000)),
                ('item_fattal_code_begin', models.DecimalField(decimal_places=0, default='-1', max_digits=1000)),
                ('item_fattal_code_end', models.DecimalField(decimal_places=0, default='9999999999', max_digits=1000)),
            ],
        ),
    ]
