# Generated by Django 3.0.7 on 2020-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0004_auto_20200628_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
