# Generated by Django 3.0.7 on 2020-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0006_auto_20200701_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
