# Generated by Django 3.0.7 on 2020-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history0', '0009_auto_20200705_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='item_unit_kindh',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('grams', 'grams'), ('kg', 'kg'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
    ]
