# Generated by Django 3.0.6 on 2020-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=80, null=True)),
                ('item_fattal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_barcode_external', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_item', models.IntegerField(blank=True, default=0, null=True)),
                ('suppliers_name', models.CharField(blank=True, choices=[('c', 'c'), ('other', 'other'), ('a', 'a'), ('b', 'b')], max_length=50, null=True)),
                ('hotel_name_transfer', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_quantity_transfer', models.IntegerField(blank=True, default='0', null=True)),
                ('item_transfer_to', models.CharField(blank=True, max_length=50, null=True)),
                ('item_transfer_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('alchol_color', models.CharField(blank=True, max_length=50, null=True)),
                ('alchol_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
