# Generated by Django 3.0.6 on 2020-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_item',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('c', 'c'), ('b', 'b'), ('a', 'a'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
