# Generated by Django 3.0.6 on 2020-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0002_auto_20200608_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('other', 'other'), ('b', 'b'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
