# Generated by Django 3.0.6 on 2020-06-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0003_auto_20200608_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('other', 'other'), ('c', 'c'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
