# Generated by Django 3.0.6 on 2020-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0004_auto_20200608_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_name', models.CharField(blank=True, choices=[('a', 'a'), ('c', 'c'), ('other', 'other'), ('b', 'b')], max_length=50, null=True)),
                ('suppliers_item_unit_quantity', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('suppliers_sale_leader_name', models.CharField(blank=True, max_length=50, null=True)),
                ('suppliers_sale_leader_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('suppliers_drivers_info', models.CharField(blank=True, max_length=50, null=True)),
                ('suppliers_phone_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='suppliers_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_item',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=1000),
            preserve_default=False,
        ),
    ]
