# Generated by Django 3.0.6 on 2020-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0007_auto_20200612_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('other', 'other'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('other', 'other'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('c', 'c'), ('other', 'other'), ('b', 'b'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
