# Generated by Django 3.0.6 on 2020-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0015_auto_20200616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_max',
            field=models.DecimalField(decimal_places=0, default='999999999', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_min',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('c', 'c'), ('a', 'a'), ('b', 'b')], max_length=50, null=True),
        ),
    ]
