# Generated by Django 3.0.6 on 2020-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0018_auto_20200617_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_fattal_code',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('other', 'other'), ('grams', 'grams'), ('liters', 'liters'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('other', 'other'), ('grams', 'grams'), ('liters', 'liters'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('b', 'b'), ('a', 'a'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
