# Generated by Django 3.0.6 on 2020-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0022_auto_20200617_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='webfiles1/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('units in box', 'unit_in_box'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('units in box', 'unit_in_box'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('c', 'c'), ('other', 'other'), ('b', 'b')], max_length=50, null=True),
        ),
    ]
