# Generated by Django 3.0.7 on 2020-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0031_auto_20200623_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
