# Generated by Django 3.0.7 on 2020-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0038_auto_20200625_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
