# Generated by Django 3.0.7 on 2020-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0053_auto_20200628_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issue_to_transfer',
            new_name='issue_to',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_transfer_to',
            new_name='item_issue_to',
        ),
        migrations.AddField(
            model_name='stock',
            name='item_fattal_code_issue',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
