# Generated by Django 3.0.7 on 2020-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0054_auto_20200701_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item_issue_to',
            new_name='item_name_issue',
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
