# Generated by Django 3.0.7 on 2020-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0062_auto_20200706_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktemp',
            name='formisokk',
        ),
        migrations.AddField(
            model_name='stocktemp',
            name='formempty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktemp',
            name='formisok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
