# Generated by Django 3.0.6 on 2020-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20200616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='os',
            field=models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('c', 'c'), ('a', 'a'), ('b', 'b')], max_length=50, null=True),
        ),
    ]
