# Generated by Django 3.0.7 on 2020-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_auto_20200623_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('eng_heb', 'engl_heb'), ('english', 'english'), ('full_hebrew', 'full_hebrew')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='os',
            field=models.CharField(blank=True, choices=[('linux', 'linux'), ('windows', 'windows')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('c', 'c'), ('b', 'b'), ('a', 'a'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
