# Generated by Django 3.0.7 on 2020-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0048_auto_20200627_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='gui_kind',
            field=models.CharField(blank=True, choices=[('Tkinter', 'Tkinter'), ('web', 'web')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('eng_heb', 'engl_heb'), ('full_hebrew', 'full_hebrew'), ('english', 'english')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('other', 'other'), ('a', 'a'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
