# Generated by Django 3.0.7 on 2020-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0051_auto_20200628_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('full_hebrew', 'full_hebrew'), ('eng_heb', 'engl_heb')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('c', 'c'), ('b', 'b'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
