# Generated by Django 3.0.7 on 2020-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0059_auto_20200706_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('full_hebrew', 'full_hebrew'), ('eng_heb', 'engl_heb'), ('english', 'english')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('b', 'b'), ('c', 'c'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
