# Generated by Django 3.0.7 on 2020-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0065_auto_20200710_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('full_hebrew', 'full_hebrew'), ('eng_heb', 'engl_heb')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('other', 'other'), ('c', 'c'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
