# Generated by Django 3.0.7 on 2020-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0068_auto_20200711_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='gui_kind',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('Tkinter', 'Tkinter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('full_hebrew', 'full_hebrew'), ('eng_heb', 'engl_heb'), ('english', 'english')], max_length=50, null=True),
        ),
    ]
