# Generated by Django 3.0.7 on 2020-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0072_auto_20200712_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('other', 'other'), ('c', 'c'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
