# Generated by Django 3.0.6 on 2020-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0008_auto_20200613_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('other', 'other'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_item',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('other', 'other'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('b', 'b'), ('a', 'a'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
