# Generated by Django 3.0.6 on 2020-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0012_auto_20200615_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('b', 'b'), ('a', 'a'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
