# Generated by Django 3.0.6 on 2020-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0014_auto_20200616_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_max',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_min',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('kg', 'kg'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('kg', 'kg'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('c', 'c'), ('a', 'a'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
