# Generated by Django 3.0.6 on 2020-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0017_auto_20200617_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_fattal_code_begin',
            field=models.DecimalField(decimal_places=0, default='-1', max_digits=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_fattal_code_end',
            field=models.DecimalField(decimal_places=0, default='9999999999', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_fattal_code',
            field=models.DecimalField(blank=True, decimal_places=0, default='-1', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('kg', 'kg'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('kg', 'kg'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('other', 'other'), ('c', 'c'), ('a', 'a')], max_length=50, null=True),
        ),
    ]
