# Generated by Django 3.0.6 on 2020-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0021_auto_20200617_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('units in box', 'unit_in_box'), ('liters', 'liters'), ('other', 'other'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('a', 'a'), ('other', 'other'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
