# Generated by Django 3.0.7 on 2020-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0027_auto_20200621_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
