# Generated by Django 3.0.7 on 2020-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0029_auto_20200621_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
