# Generated by Django 3.0.7 on 2020-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0034_auto_20200623_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sub_category_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='suppliers_fattal_code',
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('liters', 'liters'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('liters', 'liters'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_item_unit_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('c', 'c'), ('b', 'b'), ('a', 'a'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
