# Generated by Django 3.0.7 on 2020-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0035_auto_20200624_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_item_unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='supplierinformation',
            name='suppliers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
