# Generated by Django 3.0.7 on 2020-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0046_auto_20200626_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('kg', 'kg'), ('grams', 'grams'), ('units in box', 'unit_in_box'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
