# Generated by Django 3.0.7 on 2020-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0050_auto_20200627_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='hotel_name_transfer',
            new_name='issue_to_transfer',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hotel_quantity_transfer',
        ),
        migrations.AddField(
            model_name='stock',
            name='issue_quantity_transfer',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters')], max_length=50, null=True),
        ),
    ]
