# Generated by Django 3.0.7 on 2020-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0066_auto_20200710_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('units in box', 'unit_in_box'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('units in box', 'unit_in_box'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('units in box', 'unit_in_box'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktemp',
            name='item_unit_kind_issue',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('units in box', 'unit_in_box'), ('other', 'other'), ('liters', 'liters'), ('grams', 'grams')], max_length=50, null=True),
        ),
    ]
