# Generated by Django 3.0.7 on 2020-07-10 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0067_auto_20200710_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktemp',
            name='DateIssue',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktemp',
            name='item_unit_kind_issue',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('kg', 'kg'), ('grams', 'grams')], max_length=50, null=True),
        ),
    ]
