# Generated by Django 3.0.7 on 2020-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0069_auto_20200711_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcholList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alchol_kind', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='alchol_color',
        ),
        migrations.AddField(
            model_name='stock',
            name='alchol_Sticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktemp',
            name='item_unit_kind_issue',
            field=models.CharField(blank=True, choices=[('liters', 'liters'), ('other', 'other'), ('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg')], max_length=50, null=True),
        ),
    ]
