# Generated by Django 3.0.7 on 2020-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0070_auto_20200711_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alchol_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('Departments', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlcholList',
        ),
        migrations.RenameField(
            model_name='stocktemp',
            old_name='issue_to',
            new_name='item_transfer_to',
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktemp',
            name='item_unit_kind_issue',
            field=models.CharField(blank=True, choices=[('units in box', 'unit_in_box'), ('grams', 'grams'), ('kg', 'kg'), ('liters', 'liters'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
