# Generated by Django 3.0.7 on 2020-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory1', '0073_auto_20200712_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('grams', 'grams'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_fattal_code',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('grams', 'grams'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_item_unit_kind',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('grams', 'grams'), ('units in box', 'unit_in_box')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocktemp',
            name='item_unit_kind_issue',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('kg', 'kg'), ('liters', 'liters'), ('grams', 'grams'), ('units_in_box', 'unit_in_box')], max_length=50, null=True),
        ),
    ]
