# Generated by Django 3.0.6 on 2020-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20200616_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('b', 'b'), ('c', 'c'), ('a', 'a'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
