# Generated by Django 3.0.7 on 2020-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_auto_20200621_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('full_hebrew', 'full_hebrew'), ('english', 'english'), ('eng_heb', 'engl_heb')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
