# Generated by Django 3.0.7 on 2020-06-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_auto_20200622_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('full_hebrew', 'full_hebrew'), ('eng_heb', 'engl_heb'), ('english', 'english')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('other', 'other'), ('c', 'c')], max_length=50, null=True),
        ),
    ]
