# Generated by Django 3.0.7 on 2020-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0053_auto_20200701_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='gui_kind',
            field=models.CharField(blank=True, choices=[('Tkinter', 'Tkinter'), ('web', 'web')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='lang',
            field=models.CharField(blank=True, choices=[('eng_heb', 'engl_heb'), ('english', 'english'), ('full_hebrew', 'full_hebrew')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='os',
            field=models.CharField(blank=True, choices=[('linux', 'linux'), ('windows', 'windows')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='suppliers_name',
            field=models.CharField(blank=True, choices=[('c', 'c'), ('a', 'a'), ('b', 'b'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
